name: Build application and publish the artifects

on:
  push:
    branches: [ "main" ]
    
jobs: 
    build:
        name: Build
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@latest
      
          - name: Setup node
            uses: actions/setup-node@lastest
            with:
               node-version: 22.12.0
               cache: npm
          
          - name: Install
            run: npm ci

          - name: Compile
            run: npm run build
        
          - name: Upload artifacts
            uses: actions/upload-artifact@latest
            with:
              name: frontend-assets
              path: dist/
      
